<?xml version="1.0"?>
<package format="3">
  <name>dual_arm_lift_coordinator</name>
  <version>0.1.0</version>
  <description>RM65 网关只读 HEALTH TCP 客户端。</description>
  <maintainer email="maintainer@example.invalid">dual_arm_lift maintainers</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
